const express= require("express");
const router=express.Router();
const {createPost}=require('../controller/postCon');
const { likeController, unLikeController } = require("../controller/likeCon");
const { createCommentCon, deleteCommentCon } = require("../controller/commentCon");
router.post('/createPost',createPost);
router.post('/likePost/:postId',likeController);
router.delete('/unLikePost/:postId',unLikeController);
router.post('/createComment/:postId',createCommentCon);
router.delete('/deleteComment/:postId',deleteCommentCon);
module.exports=router;