const express= require("express");
const router=express.Router();
const {createPost}=require('../controller/postCon');
const { likeController, unLikeController } = require("../controller/likeCon");
const { createCommentCon, deleteCommentCon } = require("../controller/commentCon");
router.post('/createPost',createPost);
router.post('/likes/like',likeController);
router.delete('/likes/unLike',unLikeController);
router.post('/posts/:postId/createComment',createCommentCon);
router.delete('/posts/:postId/deleteComment/:commentId',deleteCommentCon);
module.exports=router;