const express= require("express");
const router=express.Router();
const {createPost}=require('../controller/postCon');
const { likeController, unLikeController } = require("../controller/likeCon");
const { createCommentCon, deleteCommentCon } = require("../controller/commentCon");
router.post('/createPost',createPost);
router.post('/posts/:postId/likePost',likeController);
router.delete('/posts/:postId/unLikePost/:likeId',unLikeController);
router.post('/createComment/:postId',createCommentCon);
router.delete('/deleteComment/:postId/:commentId',deleteCommentCon);
module.exports=router;